version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    #Si están usando este puerto recomiendo que lo cambien
      - "8084:8084"
    container_name: bank_queue_system